import Vue from "vue";
import Article from "~/components/Article.vue";
import ArticleOverview from "~/components/ArticleOverview.vue";
import Blank from "~/components/Blank.vue";
import Button from "~/components/Button.vue";
import ButtonGroup from "~/components/ButtonGroup.vue";
import CallToAction from "~/components/CallToAction.vue";
import CallToAction2Col from "~/components/CallToAction2Col.vue";
import CallToActionSmall from "~/components/CallToActionSmall.vue";
import CallToActionWideImage from "~/components/CallToActionWideImage.vue";
import Column from "~/components/Column.vue";
import Feature from "~/components/Feature.vue";
import FeatureList from "~/components/FeatureList.vue";
import Footer from "~/components/Footer.vue";
import Header from "~/components/Header.vue";
import HeaderInColumns from "~/components/HeaderInColumns.vue";
import Headline from "~/components/Headline.vue";
import Icon from "~/components/Icon.vue";
import Image from "~/components/Image.vue";
import LogoList from "~/components/LogoList.vue";
import Markdown from "~/components/Markdown.vue";
import Nav from "~/components/Nav.vue";
import NavItem from "~/components/NavItem.vue";
import Page from "~/components/Page.vue";
import Paragraph from "~/components/Paragraph.vue";
import Row from "~/components/Row.vue";

Vue.component("page", Page);
Vue.component("call_to_action", CallToAction);
Vue.component("call_to_action_2_col", CallToAction2Col);
Vue.component("call_to_action_small", CallToActionSmall);
Vue.component("call_to_action_wide_image", CallToActionWideImage);
Vue.component("button", Button);
Vue.component("feature_list", FeatureList);
Vue.component("feature", Feature);
Vue.component("header", Header);
Vue.component("nav_item", NavItem);
Vue.component("blank", Blank);
Vue.component("row", Row);
Vue.component("button_group", ButtonGroup);
Vue.component("logo_list", LogoList);
Vue.component("column", Column);
Vue.component("icon", Icon);
Vue.component("paragraph", Paragraph);
Vue.component("headline", Headline);
Vue.component("image", Image);
Vue.component("footer", Footer);
Vue.component("nav", Nav);
Vue.component("article", Article);
Vue.component("article_overview", ArticleOverview);
Vue.component("header_in_columns", HeaderInColumns);
Vue.component("markdown", Markdown);
