on:
  release:
    types: [created]

env:
  NODE_VERSION: '14.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: yarn install, generate
      run: |
        yarn
        yarn generate
    - name: publish to azure static site
      uses: tibor19/static-website-deploy@v1
      with:
        enabled-static-website: 'true'
        folder: 'dist'
        connection-string: ${{ secrets.STORAGE_CONNECTION_STRING }}
